/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import LogicPackage.Modelo;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class EditarReceita extends javax.swing.JFrame {
 Modelo l;
    /**
     * Creates new form EditarReceita
     */
    public EditarReceita(Modelo l) {
        initComponents();
        this.l=l;
    }
        public EditarReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bUpload = new javax.swing.JButton();
        lTituloR = new javax.swing.JLabel();
        bAcrescentarIngrediente = new javax.swing.JButton();
        lTituloReceita = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        testAreaMetodoDePreparacao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        listIngSelec = new javax.swing.JList<>();
        lnºpessoas = new javax.swing.JLabel();
        lingredientesselecionados = new javax.swing.JLabel();
        bGuardarReceita = new javax.swing.JButton();
        lupoadImagem = new javax.swing.JLabel();
        bEliminaReceita = new javax.swing.JButton();
        lTipoIngrediente = new javax.swing.JLabel();
        bVoltaA = new javax.swing.JButton();
        lingredientesDisponiveis = new javax.swing.JLabel();
        textFieldTituloReceita = new javax.swing.JTextField();
        lmetododepreparacao = new javax.swing.JLabel();
        textFieldNPessoas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIngDisp = new javax.swing.JList<>();
        boxTipoIngrediente = new javax.swing.JComboBox<>();
        bEliminarR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bUpload.setText("Upload");
        bUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUploadActionPerformed(evt);
            }
        });

        lTituloR.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lTituloR.setText("Editar Receita");

        bAcrescentarIngrediente.setText("Acrescentar Ingrediente");
        bAcrescentarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcrescentarIngredienteActionPerformed(evt);
            }
        });

        lTituloReceita.setText("Titulo da Receita:");

        testAreaMetodoDePreparacao.setColumns(20);
        testAreaMetodoDePreparacao.setRows(5);
        jScrollPane2.setViewportView(testAreaMetodoDePreparacao);

        listIngSelec.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listIngSelec);

        lnºpessoas.setText("Nº Pessoas:");

        lingredientesselecionados.setText("Ingredientes Selecionados:");

        bGuardarReceita.setText("Guardar Receita");
        bGuardarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarReceitaActionPerformed(evt);
            }
        });

        lupoadImagem.setText("Upload de Imagem");

        bEliminaReceita.setText("Eliminar Receita");
        bEliminaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminaReceitaActionPerformed(evt);
            }
        });

        lTipoIngrediente.setText("Tipo Ingrediente:");

        bVoltaA.setText("Voltar atrás");
        bVoltaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltaAActionPerformed(evt);
            }
        });

        lingredientesDisponiveis.setText("Ingredientes Disponiveis:");

        lmetododepreparacao.setText("Método de Preparação:");

        jScrollPane1.setViewportView(listIngDisp);

        boxTipoIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carne", "Peixe", "Vegetal", "Fruta", "Cereal", "Lacticinios", "Leguminosas", "Oleos" }));
        boxTipoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoIngredienteActionPerformed(evt);
            }
        });

        bEliminarR.setText("Eliminar Ingrediente");
        bEliminarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bGuardarReceita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bEliminaReceita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bVoltaA)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bEliminarR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bAcrescentarIngrediente))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lingredientesselecionados)
                                        .addComponent(lmetododepreparacao)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(235, 235, 235)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lingredientesDisponiveis)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lupoadImagem)
                                            .addGap(18, 18, 18)
                                            .addComponent(bUpload))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lTipoIngrediente)
                                            .addGap(18, 18, 18)
                                            .addComponent(boxTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(lTituloR, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lTituloReceita)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldTituloReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textFieldNPessoas)
                                        .addGap(109, 109, 109))))
                            .addComponent(lnºpessoas))
                        .addContainerGap(99, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lTituloR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lupoadImagem)
                                    .addComponent(bUpload)))
                            .addComponent(boxTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTituloReceita)
                            .addComponent(textFieldTituloReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnºpessoas)
                            .addComponent(textFieldNPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lingredientesselecionados)
                    .addComponent(lingredientesDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAcrescentarIngrediente)
                    .addComponent(bEliminarR))
                .addGap(18, 18, 18)
                .addComponent(lmetododepreparacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardarReceita)
                    .addComponent(bEliminaReceita)
                    .addComponent(bVoltaA))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bUploadActionPerformed

    private void bAcrescentarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcrescentarIngredienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bAcrescentarIngredienteActionPerformed

    private void boxTipoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoIngredienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boxTipoIngredienteActionPerformed

    private void bEliminarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarRActionPerformed

    private void bGuardarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bGuardarReceitaActionPerformed

    private void bEliminaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminaReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminaReceitaActionPerformed

    private void bVoltaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVoltaAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcrescentarIngrediente;
    private javax.swing.JButton bEliminaReceita;
    private javax.swing.JButton bEliminarR;
    private javax.swing.JButton bGuardarReceita;
    private javax.swing.JButton bUpload;
    private javax.swing.JButton bVoltaA;
    private javax.swing.JComboBox<String> boxTipoIngrediente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lTipoIngrediente;
    private javax.swing.JLabel lTituloR;
    private javax.swing.JLabel lTituloReceita;
    private javax.swing.JLabel lingredientesDisponiveis;
    private javax.swing.JLabel lingredientesselecionados;
    private javax.swing.JList<String> listIngDisp;
    private javax.swing.JList<String> listIngSelec;
    private javax.swing.JLabel lmetododepreparacao;
    private javax.swing.JLabel lnºpessoas;
    private javax.swing.JLabel lupoadImagem;
    private javax.swing.JTextArea testAreaMetodoDePreparacao;
    private javax.swing.JTextField textFieldNPessoas;
    private javax.swing.JTextField textFieldTituloReceita;
    // End of variables declaration//GEN-END:variables
}
