/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import LogicPackage.Modelo;
import LogicPackage.Receita;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ListarReceita extends javax.swing.JFrame {

    Modelo l;
    ArrayList<Receita> receitas;
    DefaultListModel<String> model;

    /**
     * Creates new form ListarReceita
     */
    public ListarReceita(Modelo l) {
        l.recuperaReceitas();
        this.l = l;
        this.receitas = l.getLivroReceitas().getReceitas();
        initComponents();
        preenche();
    }

    public ListarReceita() {
        initComponents();
    }

    private void preenche() {

        model = new DefaultListModel<>();

        for (Receita r : receitas) {
            model.addElement(r.getNome());
        }

        lListaR.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        bVerReceita = new javax.swing.JButton();
        bInserirReceita = new javax.swing.JButton();
        bEditarReceita = new javax.swing.JButton();
        bEliminarReceita = new javax.swing.JButton();
        bVoltarAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lListaR = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lTitulo.setText("Lista de Receitas");

        bVerReceita.setText("Ver Receita");
        bVerReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerReceitaActionPerformed(evt);
            }
        });

        bInserirReceita.setText("Inserir Receita");
        bInserirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirReceitaActionPerformed(evt);
            }
        });

        bEditarReceita.setText("Editar Receita");
        bEditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarReceitaActionPerformed(evt);
            }
        });

        bEliminarReceita.setText("Eliminar Receita");
        bEliminarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarReceitaActionPerformed(evt);
            }
        });

        bVoltarAtras.setText("Voltar atrás");
        bVoltarAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAtrasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lListaR);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bEliminarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bEditarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInserirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVerReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltarAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(lTitulo)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lTitulo)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bVerReceita)
                        .addGap(18, 18, 18)
                        .addComponent(bInserirReceita)
                        .addGap(18, 18, 18)
                        .addComponent(bEditarReceita)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminarReceita)
                        .addGap(162, 162, 162)
                        .addComponent(bVoltarAtras))
                    .addComponent(jScrollPane1))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEliminarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarReceitaActionPerformed
        int i = lListaR.getSelectedIndex();
        if (i < 0) {
            return;
        }

        if (!l.eliminaReceita(i)) {
            return;
        }

        model.remove(i);
    }//GEN-LAST:event_bEliminarReceitaActionPerformed

    private void bVerReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerReceitaActionPerformed
        int i = lListaR.getSelectedIndex();
        if (i < 0) {
            return;
        }

        VerReceita vr = new VerReceita(l, receitas.get(i), this);
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVerReceitaActionPerformed

    private void bInserirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirReceitaActionPerformed
        InserirReceita ir = new InserirReceita(l, this);
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bInserirReceitaActionPerformed

    private void bEditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarReceitaActionPerformed
        ListarReceita lr = this;

        if (lListaR.getSelectedIndex() < 0) {
            return;
        }

        int i = lListaR.getSelectedIndex();

        EditarReceita ed = new EditarReceita(l, receitas.get(i), i, lr);
        ed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bEditarReceitaActionPerformed

    private void bVoltarAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAtrasActionPerformed
        MenuInicial mi = new MenuInicial(l);
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVoltarAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditarReceita;
    private javax.swing.JButton bEliminarReceita;
    private javax.swing.JButton bInserirReceita;
    private javax.swing.JButton bVerReceita;
    private javax.swing.JButton bVoltarAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lListaR;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
