/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import LogicPackage.Modelo;
import LogicPackage.ReceitaCompativel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author joaom
 */
public class ProcurarReceita extends javax.swing.JFrame {

    Modelo l;
    DefaultListModel<String> model;
    DefaultListModel<String> m;
    ArrayList<String> ingredientes;
    ArrayList<ReceitaCompativel> rCompativel;

    /**
     * Creates new form ProcurarReceita
     */
    public ProcurarReceita(Modelo l) {
        initComponents();
        m = new DefaultListModel<>();
        model = new DefaultListModel<>();
        ingredientes = new ArrayList<>();
        rCompativel = new ArrayList<>();
        this.l = l;
    }

    public ProcurarReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lProcurarreceitas = new javax.swing.JLabel();
        lIngredienteSelecionados = new javax.swing.JLabel();
        lingredienteDisp = new javax.swing.JLabel();
        LTipoIngrediente = new javax.swing.JLabel();
        bEliminarReceita = new javax.swing.JButton();
        bAcrescentarReceita = new javax.swing.JButton();
        bProcuraR = new javax.swing.JButton();
        bEliminaI = new javax.swing.JButton();
        bEditarReceita = new javax.swing.JButton();
        bVoltaratrás = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listReceitasEncontradas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstIngSelec = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstIngDisp = new javax.swing.JList<>();
        boxTipoIngrediente = new javax.swing.JComboBox<>();
        bVerReceita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 550));

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 550));

        lProcurarreceitas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lProcurarreceitas.setText("Procurar Receitas");

        lIngredienteSelecionados.setText("Ingredientes Selecionados");

        lingredienteDisp.setText("Ingredientes Disponiveis");

        LTipoIngrediente.setText("Tipo de Ingrediente");

        bEliminarReceita.setText("Eliminar receita");
        bEliminarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarReceitaActionPerformed(evt);
            }
        });

        bAcrescentarReceita.setText("Acrescentar Ingrediente");
        bAcrescentarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcrescentarReceitaActionPerformed(evt);
            }
        });

        bProcuraR.setText("Procurar Receita");
        bProcuraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcuraRActionPerformed(evt);
            }
        });

        bEliminaI.setText("Eliminar Ingrediente");
        bEliminaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminaIActionPerformed(evt);
            }
        });

        bEditarReceita.setText("Editar Receita");
        bEditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarReceitaActionPerformed(evt);
            }
        });

        bVoltaratrás.setText("Voltar atrás");
        bVoltaratrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltaratrásActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listReceitasEncontradas);

        jScrollPane3.setViewportView(lstIngSelec);

        lstIngDisp.setModel(boxTipoIngrediente.getModel());
        jScrollPane4.setViewportView(lstIngDisp);

        boxTipoIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carne", "Peixe", "Vegetal", "Fruta", "Cereal", "Lacticinios", "Leguminosas", "Oleos" }));
        boxTipoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoIngredienteActionPerformed(evt);
            }
        });

        bVerReceita.setText("Ver Receita");
        bVerReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(lProcurarreceitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lIngredienteSelecionados)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bProcuraR)
                                .addGap(42, 42, 42)
                                .addComponent(bEliminaI)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAcrescentarReceita))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lingredienteDisp)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LTipoIngrediente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boxTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bVerReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65)
                                .addComponent(bEditarReceita)
                                .addGap(48, 48, 48)
                                .addComponent(bEliminarReceita)
                                .addGap(191, 191, 191)
                                .addComponent(bVoltaratrás))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LTipoIngrediente)
                            .addComponent(boxTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(lingredienteDisp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lProcurarreceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lIngredienteSelecionados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bProcuraR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminaI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAcrescentarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVoltaratrás, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVerReceita))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bProcuraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcuraRActionPerformed
        
        m.removeAllElements();
        if (ingredientes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não tem ingredientes selecionados!", "Warning",
                 JOptionPane.WARNING_MESSAGE);
            return;
        }

        rCompativel = l.getLivroReceitas().pesquisaReceitas(ingredientes);

        if (rCompativel.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não foram encontradas receitas compativéis!", "Warning",
                 JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (ReceitaCompativel r : rCompativel) {
            m.addElement(r.getReceita().getNome() + " " + r.getPercentagem() + "%");
        }

        listReceitasEncontradas.setModel(m);
    }//GEN-LAST:event_bProcuraRActionPerformed

    private void bEliminaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminaIActionPerformed
        if (lstIngSelec.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Deve selecionar pelo menos um ingrediente", "Warning",
                 JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (int i = 0; i < ingredientes.size(); i++) {
            if (ingredientes.get(i).equals(lstIngSelec.getSelectedValue())) {
                ingredientes.remove(i);
            }
        }

        model.remove(lstIngSelec.getSelectedIndex());
        lstIngSelec.setModel(model);
    }//GEN-LAST:event_bEliminaIActionPerformed

    private void bEditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarReceitaActionPerformed
        ProcurarReceita r = this;

        if (listReceitasEncontradas.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Deve selecionar uma receita!", "Warning",
                 JOptionPane.WARNING_MESSAGE);
            return;
        }
        int i = listReceitasEncontradas.getSelectedIndex();

        EditarReceita ed = new EditarReceita(l, rCompativel.get(i).getReceita(), rCompativel.get(i).getId(), r);
        ed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bEditarReceitaActionPerformed

    private void bEliminarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarReceitaActionPerformed
        int i = listReceitasEncontradas.getSelectedIndex();
        if (i < 0) {
            return;
        }

        if (!l.eliminaReceita(rCompativel.get(i).getId())) {
            JOptionPane.showMessageDialog(null, "Deve selecionar uma receita!", "Warning",
                 JOptionPane.WARNING_MESSAGE);
            return;
        }

        m.remove(i);
        listReceitasEncontradas.setModel(m);
        rCompativel.remove(i);
    }//GEN-LAST:event_bEliminarReceitaActionPerformed

    private void bVoltaratrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltaratrásActionPerformed
        MenuInicial mi = new MenuInicial(l);
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVoltaratrásActionPerformed

    private void bAcrescentarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcrescentarReceitaActionPerformed

        for (String s : ingredientes) {
            if (s.equals(lstIngDisp.getSelectedValue())) {
                return;
            }
        }

        lstIngSelec.setModel(model);
        ingredientes.add(lstIngDisp.getSelectedValue());
        model.addElement(lstIngDisp.getSelectedValue());
    }//GEN-LAST:event_bAcrescentarReceitaActionPerformed

    private void boxTipoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoIngredienteActionPerformed
        lstIngDisp.setModel(l.returnNomeIngredientes(boxTipoIngrediente.getItemAt(boxTipoIngrediente.getSelectedIndex())));
    }//GEN-LAST:event_boxTipoIngredienteActionPerformed

    private void bVerReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerReceitaActionPerformed
        int i = listReceitasEncontradas.getSelectedIndex();
        if (i < 0) {
            return;
        }

        VerReceita vr = new VerReceita(l, rCompativel.get(i).getReceita(), this);
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVerReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcurarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcurarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcurarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcurarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcurarReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LTipoIngrediente;
    private javax.swing.JButton bAcrescentarReceita;
    private javax.swing.JButton bEditarReceita;
    private javax.swing.JButton bEliminaI;
    private javax.swing.JButton bEliminarReceita;
    private javax.swing.JButton bProcuraR;
    private javax.swing.JButton bVerReceita;
    private javax.swing.JButton bVoltaratrás;
    private javax.swing.JComboBox<String> boxTipoIngrediente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lIngredienteSelecionados;
    private javax.swing.JLabel lProcurarreceitas;
    private javax.swing.JLabel lingredienteDisp;
    private javax.swing.JList<String> listReceitasEncontradas;
    private javax.swing.JList<String> lstIngDisp;
    private javax.swing.JList<String> lstIngSelec;
    // End of variables declaration//GEN-END:variables
}
